---
apiVersion: indicatorprotocol.io/v1
kind: IndicatorDocument

metadata:
  labels:
    deployment: well-performing-deployment
    some_number: 450

spec:
  product:
    name: well-performing-component
    version: 0.0.1

  indicators:
  - name: test_performance_indicator
    promql: query_metric{source_id="$deployment"}
    thresholds:
    - level: critical
      operator: gte
      value: $some_number
