apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: indicators.indicatorprotocol.io
spec:
  group: indicatorprotocol.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: indicators
    singular: indicator
    kind: Indicator
  additionalPrinterColumns:
  - name: Product
    type: string
    description: Product for which the indicator is defined
    JSONPath: .spec.product
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  - name: Status
    type: string
    JSONPath: .status.phase
  validation:
    openAPIV3Schema:
      type: object
      required:
      - spec
      properties:
        spec:
          type: object
          required:
          - name
          - promql
          properties:
            name:
              type: string
              pattern: '[a-zA-Z_:][a-zA-Z0-9_:]*'
            promql:
              type: string
              minLength: 1
            type:
              type: string
              enum: [kpi, sli, other]
            thresholds:
              type: array
              items:
                type: object
                required:
                - level
                - operator
                - value
                properties:
                  level:
                    type: string
                  operator:
                    type: string
                    enum: [lt, lte, gt, gte, eq, neq]
                  value:
                    oneOf:
                    - type: number
                    - type: string
            alert:
              type: object
              properties:
                for:
                  type: string # not currently validated as duration
                step:
                  type: string # not currently validated as duration
            presentation:
              type: object
              properties:
                chartType:
                  type: string
                  enum: [step, bar, status, quota]
                currentValue:
                  type: boolean
                frequency:
                  type: integer
                labels:
                  type: array
                  items:
                    type: string
            documentation:
              type: object
