apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: indicatordocuments.indicatorprotocol.io
spec:
  group: indicatorprotocol.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: indicatordocuments
    singular: indicatordocument
    kind: IndicatorDocument
    shortNames:
    - id
  validation:
    openAPIV3Schema:
      type: object
      required:
      - spec
      properties:
        spec:
          type: object
          required:
          - product
          properties:
            product:
              type: object
              required:
              - name
              - version
              properties:
                name:
                  type: string
                  minLength: 1
                version:
                  type: string
                  minLength: 1
            indicators:
              type: array
              items:
                type: object
                required:
                - name
                - promql
                properties:
                  name:
                    type: string
                    pattern: '[a-zA-Z_:][a-zA-Z0-9_:]*'
                  promql:
                    type: string
                    minLength: 1
                  type:
                    type: string
                    enum: [kpi, sli, other]
                  thresholds:
                    type: array
                    items:
                      type: object
                      required:
                      - level
                      - operator
                      - value
                      properties:
                        level:
                          type: string
                        operator:
                          type: string
                          enum: [lt, lte, gt, gte, eq, neq]
                        value:
                          oneOf:
                          - type: number
                          - type: string
                  alert:
                    type: object
                    properties:
                      for:
                        type: string # not currently validated as duration
                      step:
                        type: string # not currently validated as duration
                  presentation:
                    type: object
                    properties:
                      chartType:
                        type: string
                        enum: [step, bar, status, quota]
                      currentValue:
                        type: boolean
                      frequency:
                        type: integer
                      labels:
                        type: array
                        items:
                          type: string
                  documentation:
                    type: object
            layout:
              type: object
              properties:
                owner:
                  type: string
                title:
                  type: string
                description:
                  type: string
                sections:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      description:
                        type: string
                      indicators:
                        type: array
                        items:
                          type: string # no way to validate these
